[platformio]
default_envs = c3_promini_usb

[env]
platform = espressif32@6.9.0
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions_4mb.csv
board_build.filesystem = littlefs
board_build.flash_mode = dio
board_upload.flash_size = 4MB
upload_speed = 115200
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -Wno-unused-parameter
  -DCORE_DEBUG_LEVEL=3
extra_scripts = pre:tools/pre_build.py

[env:c3_promini_usb]
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = esptool

[env:c3_promini_uart]
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=0
upload_protocol = esptool
